### PR TITLE
HIVE-26818: Beeline module misses transitive dependencies due to shading

### PR DESCRIPTION
**Pull request by zabetak**
### What changes were proposed in this pull request?
1. Do not generate the dependency-reduced-pom.xml and publish the regular pom.xml file along with the main jar file.
2. Remove some redundant explicit dependency declarations that were added to workaround the missing dependency problem from the beeline module.

### Why are the changes needed?
Due to shading, the dependecy-reduced-pom.xml file is installed in the local maven repository (~/.m2/repository/org/apache/hive/hive-beeline/4.0.0-SNAPSHOT/) for beeline. The latter indicates that the module doesn't have any transitive dependencies. If we were publishing the shaded jar that would be true but we publish the regular jar. At this point, modules which include hive-beeline as a maven dependency are broken leading to build problems and classpath errors.

For more details see HIVE-26818.

### Does this PR introduce _any_ user-facing change?
No

### Is the change a dependency upgrade?
No

### How was this patch tested?
1. Build separately main and itest modules
```
mvn clean install -DskipTests
cd itests && mvn clean install -DskipTests
```
2. Check that `TestBeelineDriver` does not throw `NoClassDefFoundError`
```
cd itests/qtest && mvn test -Dtest=TestBeeLineDriver -Dqfile=smb_mapjoin_1.q
```

### CODE REVIEW

**Review by aturoczy — APPROVED** [review]

**Review by kokila-19 — APPROVED** [review]

**Review by ayushtkn — APPROVED** [review]
LGTM
